#!/bin/sh

# script/package - packages the application for deployment

# exit on sub-module failure
set -e

cd "$(dirname "$0")/.."

# ------

echo "Deploing..."

docker tag sqs-monitor claims/sqs-monitor:latest
docker push claims/sqs-monitor

echo "Done deploing!"

# ------